version: "3.7"
services:
  eureka-server:
    image: quan/eureka-server
    ports:
      - 8761:8761
  zuul-server:
    image: quan/zuul-server
    ports:
      - 9411:9411
    environment:
      PROFILE: "default"
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: 8761
      SERVER_PORT: 9411
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: quan_local
  account-service:
    image: quan/account-service
    ports:
      - 8080:8080
    environment:
      PROFILE: "default"
      SERVER_PORT: 8080
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: 8761
      DATABASE_SERVER_PORT: 5432
      KAFKA_SERVER_URI: "kafka_server"
      KAFKA_SERVER_PORT: 9092
      ZOOKEEPER_SERVER_URI: "zookeeper_server"
      ZOOKEEPER_SERVER_PORT: 2181
      REDIS_PORT: 6379
  person-service:
    image: quan/person-service
    ports:
      - 8081:8081
    environment:
      PROFILE: "default"
      SERVER_PORT: 8081
      EUREKA_SERVER_URI: "http://eurekaserver:8761/eureka/"
      EUREKA_SERVER_PORT: 8761
      DATABASE_SERVER_PORT: 5432
      KAFKA_SERVER_URI: "kafka_server"
      KAFKA_SERVER_PORT: 9092
      ZOOKEEPER_SERVER_URI: "zookeeper_server"
      ZOOKEEPER_SERVER_PORT: 2181
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  zookeeper_server:
    image: bitnami/zookeeper
    ports:
      - 2181:2181
  kafka_server:
    image: bitnami/kafka
    ports:
      - 9092:9092
